//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMVCUI.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personel
    {
        public int Id { get; set; }
        [Display(Name = "Departman Adý")]
        [Required]
        public Nullable<int> DepartmanId { get; set; }
        [Required]
        public string Ad { get; set; }
        [Required]
        public string Soyad { get; set; }

        [Range(1399,65000,ErrorMessage ="Maaþ Alaný 1400 ile 65000 arasýnda olmalýdýr")]
        [Display(Name = "Maaþ")]
        public Nullable<short> Maas { get; set; }
        [Required]
        [Display(Name = "Doðum Tarihi")]
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        [Required]
        public bool Cinsiyet { get; set; }
        public bool EvliMi { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
